github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
vscode:
  extensions:
    - steoates.autoimport
    - coenraads.bracket-pair-colorizer-2
    - pustelto.bracketeer
    - mhutchie.git-graph
    - eamodio.gitlens
    - dsznajder.es7-react-js-snippets
    - golang.go
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
tasks:
  - name: osmosis
    before: cd osmosis || git clone https://github.com/onezoomin/osmosis
    init: cd /workspace/osmosis-local/osmosis && git pull && make -k install
    command: cd /workspace/osmosis-local/osmosis && scripts/start_testnode.sh | tee start_testnode$(date '+%Y-%m-%d').log && osmosisd start
  - name: osmosis-frontend
    before: nvm install 15 && cd osmosis-frontend || git clone https://github.com/onezoomin/osmosis-frontend
    init: cd /workspace/osmosis-local/osmosis-frontend && git pull && nvm use 15 && yarn && yarn build
    command: cd /workspace/osmosis-local/osmosis-frontend && nvm use 15 && yarn dev
    openMode: split-right
