ports:
  - port: 8080
    visibility: public
    onOpen: open-browser
  - port: 26657
    visibility: public
  - port: 1317
    visibility: public
    
tasks:
  - name: osmosis
    before: |
     (cd osmosis && git status) || git clone https://github.com/onezoomin/osmosis
     echo 'alias osmod="osmosisd --home /workspace/osmosis-local/.osmosisd"' >> ~/.bashrc.d/aliases
    init: |
      cd /workspace/osmosis-local/osmosis && git pull && make -k install && 
      cd /workspace/osmosis-local/osmosis && scripts/start_testnode.sh -c osmo-gitpod 2>&1 | tee start_testnode$(date '+%Y-%m-%d_+%T').log && 
      mv $HOME/.osmosisd /workspace/osmosis-local/
      osmod version
    command:  osmod start
  - name: osmosis-frontend
    before: nvm install 15 && cd osmosis-frontend || git clone https://github.com/onezoomin/osmosis-frontend
    init: cd /workspace/osmosis-local/osmosis-frontend && git pull && git checkout gitpod && nvm use 15 && yarn && yarn build
    command: cd /workspace/osmosis-local/osmosis-frontend && nvm use 15 && yarn dev
    openMode: split-right

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

vscode:
  extensions:
    - steoates.autoimport
    - coenraads.bracket-pair-colorizer-2
    - pustelto.bracketeer
    - mhutchie.git-graph
    - eamodio.gitlens
    - dsznajder.es7-react-js-snippets
    - golang.go
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - k--kato.intellij-idea-keybindings

